# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('secure-mobility-solution-example', ['secure-mobility-solution','csma','point-to-point'])
    obj.source = 'secure-mobility-solution-example.cc'

